name: base_bloc
description: A new Flutter package.
version: 0.0.2
author:
homepage: ""

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  bloc: 3.0.0
  flutter_bloc: 3.2.0
  meta: 1.1.8

flutter:
